Develop
EverID/everest-chainlink-consumer pull request #1
Opened 2022-07-07 10:58 UTC by dovgopoly

2022-07-07 12:29 UTC, artemskriabin requested changes

2022-07-07 12:29 UTC, artemskriabin commented on adapter/internal/adapter/main.go
> +		if response.Unit.KYCDate.Unix() != 0 {
are sure?

2022-07-08 12:15 UTC, dovgopoly commented on adapter/internal/adapter/main.go
> +		if response.Unit.KYCDate.Unix() != 0 {
fixed

2022-08-01 11:59 UTC, artemskriabin commented on contracts/UnitConsumer.sol
> +        NotFound
what is the difference between undefined and not found?

2022-08-02 13:58 UTC, dovgopoly commented on contracts/UnitConsumer.sol
> +        NotFound
"undefined" means that the request has not yet been fulfilled or an error occurred, whereas "not found" means that the request has been fulfilled, but the user passed an address that is absent in our system.

2022-08-08 13:08 UTC, artemskriabin commented on contracts/UnitConsumer.sol
> +        NotFound
add comments

2022-09-06 11:13 UTC, vnavascues reviewed
Hi, this is Victor from LinkPool. Congrats on this neat and thorough integration (e.g. cancel request)!

I left few suggestions wrt the consumer contract and the TOML spec. I share below the gists with their full implementation.

[Consumer contract](https://gist.github.com/vnavascues/135a2ea0331c4d98d271dae8d1499efb)
[TOML spec](https://gist.github.com/vnavascues/be2a7cde9da432bed2db0868436834d8)

2022-09-06 11:13 UTC, vnavascues commented on contracts/UnitConsumer.sol
> +        uint256 kycTimestamp;
`Request` timestamps can be `uint40`, making the struct size 2 slots instead of 3. This has few implications, being the most relevant ones:
  - Contract data types on struct, fulfillment function and events (optional):
    - Operator expiration time to be `uint40` (as `OPERATOR_EXPIRATION_TIME`)
    - `fulfill(bytes32, uint8, uint40)` 
  - TOML `ethabiencode` abi field can optionally reflect it `abi="(bytes32 _requestId, uint8 _status, uint40 _kycTimestamp)"`.

2022-09-06 11:13 UTC, vnavascues commented on contracts/UnitConsumer.sol
> +        Chainlink.Request memory request = buildChainlinkRequest(
Due to this Any API (Direct Request) integration leveraging the new Multi Word Response, is more accurate building and sending an [Operator request](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.7/Operator.sol#L131) (probably the most relevant thing is that the ChainlinkClient library sets [dataVersion as 2](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/ChainlinkClient.sol#L150)).

[buildOperatorRequest](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/ChainlinkClient.sol#L62)
[sendOperatorRequest](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/ChainlinkClient.sol#L121)

2022-09-06 11:13 UTC, vnavascues commented on contracts/UnitConsumer.sol
> +        request.add("address", Strings.toHexString(_revealee));
If `_revealee` is always going to be an EVM address (that's the case, isn't it?) there is no need to send it as string, just encode it (no need for 3rd party libs).

```solidity
request.addBytes("address", abi.encode(_revealee));
```

Then it has to be decoded on the TOML spec:

```toml
    decode_cbor     [
                     type=cborparse
                     data="$(decode_log.data)"
                    ]
    decode_address  [
                     type=ethabidecode
                     abi="address address"
                     data="$(decode_cbor.address)"
                    ]
    fetch           [
                     type=bridge
                     name="units-external-adapter"
                     requestData=<{
                        "id": $(jobSpec.externalJobID),
                        "data": {"address": $(decode_address.address)}
                     }>
                    ]
```

2022-10-24 12:15 UTC, artemskriabin approved these changes

2022-10-24 12:34 UTC, merged